
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_DOUBLE = 30;
  public static final int T_WHILE = 46;
  public static final int T_POW = 16;
  public static final int T_GREATERTHAN = 22;
  public static final int T_ELSE = 40;
  public static final int T_NOTEQUAL = 19;
  public static final int T_CONTINUE = 45;
  public static final int T_LIST = 53;
  public static final int T_APPEND = 56;
  public static final int P_RIGHT = 8;
  public static final int T_XOR = 27;
  public static final int T_INT = 29;
  public static final int T_ROUND = 50;
  public static final int T_CARACTER = 6;
  public static final int T_FOR = 43;
  public static final int T_LESSTHAN = 20;
  public static final int T_NOT = 28;
  public static final int T_AND = 26;
  public static final int T_CONST = 35;
  public static final int T_CADENA = 4;
  public static final int T_PRINTLN = 2;
  public static final int UMENOS = 60;
  public static final int T_DO = 47;
  public static final int T_DOT = 55;
  public static final int T_INCREMENT = 37;
  public static final int EOF = 0;
  public static final int T_MINUS = 13;
  public static final int T_START_WITH = 58;
  public static final int error = 1;
  public static final int T_NEW = 54;
  public static final int T_BRACEDER = 49;
  public static final int T_MOD = 17;
  public static final int T_COMMA = 51;
  public static final int T_BRACEIZ = 48;
  public static final int T_DECREMENT = 38;
  public static final int T_STRING = 31;
  public static final int T_BRACKETDER = 42;
  public static final int T_CHARACTER = 36;
  public static final int T_DECIMAL = 5;
  public static final int T_GREATERTHANEQUAL = 23;
  public static final int T_SEMICOLON = 9;
  public static final int T_BOOL = 32;
  public static final int T_EQUAL = 24;
  public static final int T_LENGTH = 59;
  public static final int P_LEFT = 7;
  public static final int T_PLUS = 12;
  public static final int T_OR = 25;
  public static final int T_BREAK = 44;
  public static final int T_DIVIDE = 15;
  public static final int T_BOLEANO = 10;
  public static final int T_REMOVE = 57;
  public static final int T_IF = 39;
  public static final int T_TIMES = 14;
  public static final int T_LESSTHANEQUAL = 21;
  public static final int T_ID = 33;
  public static final int T_COLON = 11;
  public static final int T_VOID = 52;
  public static final int T_BRACKETIZ = 41;
  public static final int T_VAR = 34;
  public static final int T_ENTERO = 3;
  public static final int T_TWOEQUAL = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_PRINTLN",
  "T_ENTERO",
  "T_CADENA",
  "T_DECIMAL",
  "T_CARACTER",
  "P_LEFT",
  "P_RIGHT",
  "T_SEMICOLON",
  "T_BOLEANO",
  "T_COLON",
  "T_PLUS",
  "T_MINUS",
  "T_TIMES",
  "T_DIVIDE",
  "T_POW",
  "T_MOD",
  "T_TWOEQUAL",
  "T_NOTEQUAL",
  "T_LESSTHAN",
  "T_LESSTHANEQUAL",
  "T_GREATERTHAN",
  "T_GREATERTHANEQUAL",
  "T_EQUAL",
  "T_OR",
  "T_AND",
  "T_XOR",
  "T_NOT",
  "T_INT",
  "T_DOUBLE",
  "T_STRING",
  "T_BOOL",
  "T_ID",
  "T_VAR",
  "T_CONST",
  "T_CHARACTER",
  "T_INCREMENT",
  "T_DECREMENT",
  "T_IF",
  "T_ELSE",
  "T_BRACKETIZ",
  "T_BRACKETDER",
  "T_FOR",
  "T_BREAK",
  "T_CONTINUE",
  "T_WHILE",
  "T_DO",
  "T_BRACEIZ",
  "T_BRACEDER",
  "T_ROUND",
  "T_COMMA",
  "T_VOID",
  "T_LIST",
  "T_NEW",
  "T_DOT",
  "T_APPEND",
  "T_REMOVE",
  "T_START_WITH",
  "T_LENGTH",
  "UMENOS"
  };
}

