
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_POW = 15;
  public static final int T_PLUS = 11;
  public static final int P_RIGHT = 8;
  public static final int T_BOLEANO = 10;
  public static final int T_MOD = 16;
  public static final int T_DECIMAL = 4;
  public static final int EOF = 0;
  public static final int T_CARACTER = 5;
  public static final int P_LEFT = 7;
  public static final int T_PRINTLN = 6;
  public static final int T_TIMES = 13;
  public static final int T_CADENA = 3;
  public static final int error = 1;
  public static final int T_DIVIDE = 14;
  public static final int T_SEMICOLON = 9;
  public static final int T_MINUS = 12;
  public static final int T_ENTERO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_ENTERO",
  "T_CADENA",
  "T_DECIMAL",
  "T_CARACTER",
  "T_PRINTLN",
  "P_LEFT",
  "P_RIGHT",
  "T_SEMICOLON",
  "T_BOLEANO",
  "T_PLUS",
  "T_MINUS",
  "T_TIMES",
  "T_DIVIDE",
  "T_POW",
  "T_MOD"
  };
}

