
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_MOD = 16;
  public static final int T_AND = 24;
  public static final int T_CARACTER = 6;
  public static final int T_LESSTHAN = 19;
  public static final int T_BOLEANO = 10;
  public static final int T_GREATERTHANEQUAL = 22;
  public static final int T_OR = 23;
  public static final int T_NOT = 26;
  public static final int T_POW = 15;
  public static final int T_MINUS = 12;
  public static final int UMENOS = 27;
  public static final int T_DIVIDE = 14;
  public static final int P_RIGHT = 8;
  public static final int T_LESSTHANEQUAL = 20;
  public static final int T_DECIMAL = 5;
  public static final int EOF = 0;
  public static final int T_TWOEQUAL = 17;
  public static final int T_ENTERO = 3;
  public static final int T_TIMES = 13;
  public static final int T_GREATERTHAN = 21;
  public static final int error = 1;
  public static final int T_NOTEQUAL = 18;
  public static final int T_XOR = 25;
  public static final int P_LEFT = 7;
  public static final int T_SEMICOLON = 9;
  public static final int T_CADENA = 4;
  public static final int T_PLUS = 11;
  public static final int T_PRINTLN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_PRINTLN",
  "T_ENTERO",
  "T_CADENA",
  "T_DECIMAL",
  "T_CARACTER",
  "P_LEFT",
  "P_RIGHT",
  "T_SEMICOLON",
  "T_BOLEANO",
  "T_PLUS",
  "T_MINUS",
  "T_TIMES",
  "T_DIVIDE",
  "T_POW",
  "T_MOD",
  "T_TWOEQUAL",
  "T_NOTEQUAL",
  "T_LESSTHAN",
  "T_LESSTHANEQUAL",
  "T_GREATERTHAN",
  "T_GREATERTHANEQUAL",
  "T_OR",
  "T_AND",
  "T_XOR",
  "T_NOT",
  "UMENOS"
  };
}

